"""Adapter code generation.

Two modes:

  1. LLM mode (default if ANTHROPIC_API_KEY is set):
     Sends protocol + reference adapters + relevant skills + asked answers
     to Claude, asks for a complete adapter file. This is the equivalent of
     Hermes' `claude-code` skill — the agent doesn't write the code itself,
     it delegates to a coding-specialist model.

  2. Template mode (default fallback):
     A deterministic template informed by the protocol metadata. Lets the
     full demo run end-to-end with NO API key, NO network, NO LLM.
     Real users would replace this with the real LLM call.
"""

from __future__ import annotations

import argparse
import os
import re
from pathlib import Path
from typing import Dict, List

ROOT = Path(__file__).resolve().parent.parent
ADAPTERS_DIR = ROOT / "adapters"
PROTOCOLS_DIR = ROOT / "protocols"


def _read_protocol(media: str) -> str:
    path = PROTOCOLS_DIR / f"{media}.md"
    if not path.exists():
        raise FileNotFoundError(f"no protocol spec for media={media}: {path}")
    return path.read_text(encoding="utf-8")


def _read_references() -> Dict[str, str]:
    refs: Dict[str, str] = {}
    for p in ADAPTERS_DIR.glob("*.py"):
        if p.name in ("__init__.py", "base.py"):
            continue
        refs[p.stem] = p.read_text(encoding="utf-8")
    return refs


def _extract_protocol_features(spec: str) -> Dict:
    """Pull out the deterministically-templatable bits from the protocol md.

    This is intentionally simple — pattern-matching on the spec format
    we control. In LLM mode this is unnecessary; in template mode it's
    how we 'understand' the protocol enough to generate code.
    """
    f: Dict = {
        "no_bid_status": 200,
        "no_bid_body_template": '{}',
        "echo_id_in_no_bid": False,
        "request_id_field": "id",
        "slots_field": "imp",
        "slot_id_field": "tagid",
        "tmax_field": "tmax",
        "tmax_unit": "ms",
        "device_field": "device",
        "device_id_path": "oaid",
        "sig_algo": "sha256",
        "sig_input": "body_plus_ts",
        "ts_unit": "s",
        "ts_tolerance": 60,
        "price_field": "price",
        "price_unit": "float",
    }
    if "HTTP 204" in spec:
        f["no_bid_status"] = 204
        f["no_bid_body_template"] = "EMPTY"
    if re.search(r"echo\s+the\s+request\s+id", spec, flags=re.IGNORECASE):
        f["echo_id_in_no_bid"] = True
    if re.search(r"sha512", spec, flags=re.IGNORECASE):
        f["sig_algo"] = "sha512"
    if re.search(r"nonce\s*\+.*body", spec, flags=re.IGNORECASE | re.DOTALL):
        f["sig_input"] = "nonce_plus_body_sha"
    if re.search(r"price_cents", spec):
        f["price_field"] = "price_cents"
        f["price_unit"] = "cents_int"
    if re.search(r"oaid_sha256", spec):
        f["device_id_path"] = "oaid_sha256"
    if "ad_slots" in spec:
        f["slots_field"] = "ad_slots"
        f["slot_id_field"] = "slot_id"
    if "tmax_ms" in spec:
        f["tmax_field"] = "tmax_ms"
    return f


_TEMPLATE_HEADER = '''"""{media} RTA adapter — generated by agent.

Source spec: protocols/{media}.md
Reference adapters consulted: {refs}
Relevant skills applied: {skills}
"""

from __future__ import annotations

import hashlib
import hmac
import json
import secrets
import time
from typing import Dict, Optional

from .base import (
    NormalizedBid,
    NormalizedBidRequest,
    NormalizedBidResponse,
    RTAAdapter,
    WireResponse,
)


SIGNING_SECRET = b"{media}-signing-secret-demo"
BEARER_TOKEN = "{media}-bearer-token-demo"

'''


def _render_template(media: str, features: Dict, refs: List[str], skills: List[str]) -> str:
    no_bid_section = ""
    if features["no_bid_status"] == 204:
        no_bid_section = "return WireResponse(status=204, headers={}, body=None)"
    else:
        if features["echo_id_in_no_bid"]:
            no_bid_section = (
                'return WireResponse(\n'
                '            status=200,\n'
                '            headers={"Content-Type": "application/json"},\n'
                '            body=json.dumps({"id": resp.request_id, "nbr": 0}),\n'
                '        )'
            )
        else:
            no_bid_section = (
                'return WireResponse(\n'
                '            status=200,\n'
                '            headers={"Content-Type": "application/json"},\n'
                '            body=json.dumps({"nbr": 1}),\n'
                '        )'
            )

    if features["price_unit"] == "cents_int":
        bid_render = (
            '{"slot_id": b.slot_id, "price_cents": int(round(b.price * 100)), '
            '"creative_id": b.creative_id}'
        )
    else:
        bid_render = (
            '{"slot_id": b.slot_id, "price": b.price, "creative_id": b.creative_id}'
        )

    if features["sig_algo"] == "sha512" and features["sig_input"] == "nonce_plus_body_sha":
        sig_block = '''        sig = headers.get("X-Bear-Sign", "")
        nonce = headers.get("X-Bear-Nonce", "")
        bearer = headers.get("X-Bear-Auth", "")
        if not sig or not nonce or bearer != BEARER_TOKEN:
            return False
        body_sha = hashlib.sha256(body.encode("utf-8")).hexdigest()
        expected = hmac.new(
            SIGNING_SECRET,
            f"{nonce}.{body_sha}".encode("utf-8"),
            hashlib.sha512,
        ).hexdigest()
        return hmac.compare_digest(sig, expected)'''
    else:
        sig_block = '''        sig = headers.get("X-Sign", "")
        ts = headers.get("X-Ts", "")
        if not sig or not ts:
            return False
        expected = hmac.new(
            SIGNING_SECRET, f"{body}.{ts}".encode("utf-8"), hashlib.sha256
        ).hexdigest()
        return hmac.compare_digest(sig, expected)'''

    slot_field = features["slots_field"]
    slot_id_field = features["slot_id_field"]
    tmax_field = features["tmax_field"]
    device_id_path = features["device_id_path"]
    request_id_field = features["request_id_field"]

    parse_block = f'''        data = json.loads(body)
        slots = data.get("{slot_field}", [])
        device = data.get("device", {{}})
        return NormalizedBidRequest(
            request_id=data["{request_id_field}"],
            slot_ids=[s["{slot_id_field}"] for s in slots],
            device_id=device.get("{device_id_path}"),
            device_id_kind="{device_id_path}" if device.get("{device_id_path}") else None,
            floor_price=float(slots[0].get("floor", slots[0].get("floor_price", 0.0))) if slots else 0.0,
            deadline_ms=int(data.get("{tmax_field}", 80)),
            raw=data,
        )'''

    encode_bid_block = f'''        body = json.dumps({{
            "id": resp.request_id,
            "bids": [
                {bid_render}
                for b in resp.bids
            ],
        }})
        return WireResponse(
            status=200,
            headers={{"Content-Type": "application/json"}},
            body=body,
        )'''

    class_name = f"{media[0].upper() + media[1:]}Adapter"
    out = _TEMPLATE_HEADER.format(media=media, refs=", ".join(refs), skills=", ".join(skills) or "(none)")
    out += f'''
class {class_name}(RTAAdapter):
    MEDIA = "{media}"
    LATENCY_BUDGET_MS = 40

    def parse_request(self, body: str, headers: Dict[str, str]) -> NormalizedBidRequest:
{parse_block}

    def verify_signature(self, body: str, headers: Dict[str, str]) -> bool:
{sig_block}

    def encode_response(self, resp: NormalizedBidResponse) -> WireResponse:
        if resp.is_no_bid:
            {no_bid_section}
{encode_bid_block}

    def device_id_for_bidding(self, req: NormalizedBidRequest) -> Optional[str]:
        return req.device_id
'''
    return out


def generate(media: str, applied_skills: List[str], use_llm: bool = False) -> str:
    spec = _read_protocol(media)
    refs = _read_references()
    if use_llm and os.environ.get("ANTHROPIC_API_KEY"):
        return _generate_with_llm(media, spec, refs, applied_skills)
    features = _extract_protocol_features(spec)
    return _render_template(media, features, list(refs.keys()), applied_skills)


def _generate_with_llm(media: str, spec: str, refs: Dict[str, str], skills: List[str]) -> str:
    try:
        from anthropic import Anthropic  # type: ignore
    except ImportError:
        raise RuntimeError(
            "anthropic SDK not installed; pip install anthropic, or run in template mode"
        )
    client = Anthropic()
    ref_blob = "\n\n".join(
        f"### adapters/{name}.py\n```python\n{code}\n```" for name, code in refs.items()
    )
    skill_blob = "\n".join(f"- {s}" for s in skills) or "(none)"
    prompt = f"""You are extending an in-house RTA-integration codebase. Write ONE Python file
for adapters/{media}.py that subclasses RTAAdapter from adapters/base.py.

Conform to the same shape as the reference adapters below. Use the protocol
spec as ground truth. Apply the listed skills. Output ONLY the Python source
of the new file, no markdown fences, no commentary.

== protocol spec (protocols/{media}.md) ==
{spec}

== reference adapters ==
{ref_blob}

== applied skills ==
{skill_blob}
"""
    msg = client.messages.create(
        model="claude-opus-4-5",
        max_tokens=4096,
        messages=[{"role": "user", "content": prompt}],
    )
    return msg.content[0].text  # type: ignore[union-attr]


def write(media: str, source: str) -> Path:
    out = ADAPTERS_DIR / f"{media}.py"
    out.write_text(source, encoding="utf-8")
    return out


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("media")
    parser.add_argument("--skills", default="", help="comma-separated skill ids that were applied")
    parser.add_argument("--llm", action="store_true", help="use LLM mode (requires ANTHROPIC_API_KEY)")
    parser.add_argument("--print", action="store_true", help="print to stdout, do not write")
    args = parser.parse_args()
    skills = [s.strip() for s in args.skills.split(",") if s.strip()]
    src = generate(args.media, skills, use_llm=args.llm)
    if args.print:
        print(src)
        return
    p = write(args.media, src)
    print(f"wrote adapter: {p}")


if __name__ == "__main__":
    main()
